# Numpy

Numpy is a package which is created primarily for array and matrics manipulation

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
#converting list into array
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
arr1 = np.array([[1,2,4],[3,5,6]])

In [7]:
arr.ndim

1

In [8]:
arr1.ndim

2

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr1

array([[1, 2, 4],
       [3, 5, 6]])

In [11]:
mat = np.matrix(l)

In [12]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [13]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

matrix is a subclass of an array inside numpy 

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
a = arr

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[0] = 100 ## reassigning values using operatorrs

In [19]:
arr

array([100,   2,   3,   4,   5])

In [20]:
a

array([100,   2,   3,   4,   5])

### this is called shallow copy operation 
a shallow copy creates a duplicate of the original element (whether simple or complex ) but does not 
make copies of any elements referenced by the original element

In [21]:
b = np.copy(arr)

In [22]:
b

array([100,   2,   3,   4,   5])

In [23]:
b[0] = 234

In [24]:
b

array([234,   2,   3,   4,   5])

In [25]:
arr

array([100,   2,   3,   4,   5])

In [26]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [29]:
iterable = (i*i for i in range(5))

In [30]:
np.fromiter(iterable , float)  ## using fromiter we can able to generate the array

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('23 24 25' , sep =' ') # from string to array

array([23., 24., 25.])

In [32]:
np.fromstring('23,24, 25' , sep =',')

array([23., 24., 25.])

In [33]:
arr

array([100,   2,   3,   4,   5])

In [34]:
arr1

array([[1, 2, 4],
       [3, 5, 6]])

In [35]:
arr.ndim

1

In [36]:
arr1.ndim

2

In [37]:
arr.size ## will give us no of elements inside arr

5

In [38]:
arr1.size

6

In [39]:
arr1.shape

(2, 3)

In [40]:
arr1.dtype

dtype('int64')

# Numpy functionalities

In [41]:
list(range(5)) 

[0, 1, 2, 3, 4]

In [42]:
list(range(0,10)) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

range function always consider integer values

In [43]:
list(range(0.4,10.4)) 

TypeError: 'float' object cannot be interpreted as an integer

in numpy it can take flloat values as well with step size

In [44]:
np.arange(.4,10.4) 

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [45]:
np.arange(.4,10.4,0.4)  # here we can give stepsize

array([ 0.4,  0.8,  1.2,  1.6,  2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,
        4.8,  5.2,  5.6,  6. ,  6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,
        9.2,  9.6, 10. ])

In [46]:
list(np.arange(.4,10.4,0.4)) # converting array to list 

[0.4,
 0.8,
 1.2000000000000002,
 1.6,
 2.0,
 2.4,
 2.8000000000000003,
 3.2,
 3.6,
 4.0,
 4.4,
 4.800000000000001,
 5.200000000000001,
 5.6000000000000005,
 6.000000000000001,
 6.4,
 6.800000000000001,
 7.200000000000001,
 7.6000000000000005,
 8.0,
 8.4,
 8.8,
 9.200000000000001,
 9.600000000000001,
 10.000000000000002]

In [47]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [48]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [49]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.zeros((3,4,2)) # 4 rows 2 colms 3 matrices

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [53]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [54]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
arr2 = np.ones((3,4))

In [56]:
arr2+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [57]:
arr2*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [58]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [59]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
arr3 = np.eye(5)

In [61]:
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
#converting matrix into data frame
import pandas as pd

In [63]:
pd.DataFrame(arr3)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [64]:
np.random.rand(2,3) ## here mean and std can be anything

array([[0.96291072, 0.11177337, 0.73863637],
       [0.74475191, 0.87371036, 0.26542578]])

In [65]:
np.random.randn(2,3) # it will gives the data in a standard normal distribuion i,e mean = 0 std=1

array([[ 2.21396165, -0.89801208, -1.29952862],
       [ 0.10398259, -0.39474062,  1.32656439]])

In [66]:
arr4 = np.random.randint(1,5 ,(3,4))

In [67]:
arr4

array([[4, 4, 2, 4],
       [1, 4, 4, 1],
       [4, 1, 3, 4]])

In [68]:
arr4.size

12

In [69]:
arr4.shape

(3, 4)

In [70]:
arr4.reshape(6,2)

array([[4, 4],
       [2, 4],
       [1, 4],
       [4, 1],
       [4, 1],
       [3, 4]])

In [71]:
arr4.reshape(2,6)

array([[4, 4, 2, 4, 1, 4],
       [4, 1, 4, 1, 3, 4]])

In [72]:
arr4.reshape(4,-1)

array([[4, 4, 2],
       [4, 1, 4],
       [4, 1, 4],
       [1, 3, 4]])

In [73]:
arr4.reshape(4,-1234235)

array([[4, 4, 2],
       [4, 1, 4],
       [4, 1, 4],
       [1, 3, 4]])

In [74]:
arr4.reshape(2,2,3)

array([[[4, 4, 2],
        [4, 1, 4]],

       [[4, 1, 4],
        [1, 3, 4]]])

In [75]:
arr4.reshape(2,2,3,1,1,1)

array([[[[[[4]]],


         [[[4]]],


         [[[2]]]],



        [[[[4]]],


         [[[1]]],


         [[[4]]]]],




       [[[[[4]]],


         [[[1]]],


         [[[4]]]],



        [[[[1]]],


         [[[3]]],


         [[[4]]]]]])

In [76]:
arr5 = np.random.randint(1,10,(5,6))

In [77]:
arr5

array([[1, 8, 6, 8, 3, 8],
       [9, 6, 4, 2, 1, 4],
       [4, 1, 3, 5, 6, 3],
       [5, 2, 8, 7, 4, 4],
       [2, 2, 5, 1, 3, 9]])

In [78]:
arr5 > 8

array([[False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True]])

In [79]:
arr5[arr5 > 8]

array([9, 9])

In [80]:
arr5

array([[1, 8, 6, 8, 3, 8],
       [9, 6, 4, 2, 1, 4],
       [4, 1, 3, 5, 6, 3],
       [5, 2, 8, 7, 4, 4],
       [2, 2, 5, 1, 3, 9]])

In [81]:
#extracting data
arr5[0]

array([1, 8, 6, 8, 3, 8])

In [82]:
arr5[0,[0,1]]

array([1, 8])

In [83]:
arr5[2:4, [2,3]]

array([[3, 5],
       [8, 7]])

In [84]:
# Slicing and indexing 

In [85]:
arr6 = np.random.randint(1,3, (3,3))
arr7 = np.random.randint(1,3, (3,3))

In [86]:
arr6

array([[1, 1, 1],
       [2, 1, 1],
       [1, 2, 2]])

In [87]:
arr7

array([[2, 2, 1],
       [1, 1, 2],
       [2, 2, 2]])

In [88]:
arr6 + arr7

array([[3, 3, 2],
       [3, 2, 3],
       [3, 4, 4]])

In [89]:
arr6 - arr7

array([[-1, -1,  0],
       [ 1,  0, -1],
       [-1,  0,  0]])

In [90]:
arr6 * arr7 # it was done by index wise

array([[2, 2, 1],
       [2, 1, 2],
       [2, 4, 4]])

In [91]:
arr6@arr7 # normal matrix multiplication

array([[5, 5, 5],
       [7, 7, 6],
       [8, 8, 9]])

In [92]:
arr6/arr7

array([[0.5, 0.5, 1. ],
       [2. , 1. , 0.5],
       [0.5, 1. , 1. ]])

In [93]:
arr6/0

/tmp/ipykernel_78/1351048935.py:1: RuntimeWarning: divide by zero encountered in divide
  arr6/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

# Numpy - Broadcasting

In [94]:
arr8 = np.zeros((3,4))

In [95]:
arr8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
arr8+5 # here iam broadcasting this 5 to all

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [97]:
a = np.array([1,2,3,4])

In [98]:
arr8+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [99]:
b= np.array([3,4,5])

In [100]:
arr8+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [101]:
b= np.array([[3,4,5]]) # rotating the array

In [102]:
arr9 =arr8+b.T

In [103]:
b.T

array([[3],
       [4],
       [5]])

In [104]:
arr9

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [105]:
np.sqrt(arr9)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [106]:
np.log10(arr9)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [107]:
np.exp(arr9)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [108]:
np.min(arr9)

3.0

In [109]:
np.max(arr9)

5.0

# Numpy functions

In [110]:
# Numpy - array manipulation


In [111]:
array = np.random.randint(1,10 ,(4,4))

In [112]:
array

array([[3, 3, 8, 6],
       [2, 1, 5, 6],
       [1, 3, 6, 9],
       [9, 3, 9, 4]])

In [113]:
array.reshape(8,2)

array([[3, 3],
       [8, 6],
       [2, 1],
       [5, 6],
       [1, 3],
       [6, 9],
       [9, 3],
       [9, 4]])

In [114]:
array

array([[3, 3, 8, 6],
       [2, 1, 5, 6],
       [1, 3, 6, 9],
       [9, 3, 9, 4]])

In [115]:
array.T ## matrix rotation

array([[3, 2, 1, 9],
       [3, 1, 3, 3],
       [8, 5, 6, 9],
       [6, 6, 9, 4]])

In [116]:
array.flatten()

array([3, 3, 8, 6, 2, 1, 5, 6, 1, 3, 6, 9, 9, 3, 9, 4])

In [117]:
array

array([[3, 3, 8, 6],
       [2, 1, 5, 6],
       [1, 3, 6, 9],
       [9, 3, 9, 4]])

In [118]:
np.expand_dims(array , axis=1) # expanded to 3 dimension

array([[[3, 3, 8, 6]],

       [[2, 1, 5, 6]],

       [[1, 3, 6, 9]],

       [[9, 3, 9, 4]]])

In [119]:
np.expand_dims(array , axis=0)

array([[[3, 3, 8, 6],
        [2, 1, 5, 6],
        [1, 3, 6, 9],
        [9, 3, 9, 4]]])

In [120]:
data = np.array([[1] , [2] , [3]])

In [121]:
np.squeeze(data) # it will squeeze the 3 dim to 1 dim

array([1, 2, 3])

In [122]:
np.repeat(data , 2)

array([1, 1, 2, 2, 3, 3])

In [123]:
np.repeat(data , 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [124]:
np.roll(data , 3)

array([[1],
       [2],
       [3]])

In [125]:
np.roll(data , 2)

array([[2],
       [3],
       [1]])

In [126]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [127]:
#Numpy - Binary operations.

In [128]:
array1 = np.random.randint(1,10 , (3,4))
array2 = np.random.randint(1,10 , (3,4))

In [129]:
array1

array([[9, 6, 9, 4],
       [5, 5, 1, 3],
       [8, 6, 5, 7]])

In [130]:
array2

array([[2, 3, 3, 5],
       [2, 8, 2, 9],
       [5, 6, 6, 3]])

In [131]:
array1 + array2

array([[11,  9, 12,  9],
       [ 7, 13,  3, 12],
       [13, 12, 11, 10]])

In [132]:
array1 * array2

array([[18, 18, 27, 20],
       [10, 40,  2, 27],
       [40, 36, 30, 21]])

In [133]:
array1 / array2

array([[4.5       , 2.        , 3.        , 0.8       ],
       [2.5       , 0.625     , 0.5       , 0.33333333],
       [1.6       , 1.        , 0.83333333, 2.33333333]])

In [134]:
array1-array2

array([[ 7,  3,  6, -1],
       [ 3, -3, -1, -6],
       [ 3,  0, -1,  4]])

In [135]:
array1**array2

array([[    81,    216,    729,   1024],
       [    25, 390625,      1,  19683],
       [ 32768,  46656,  15625,    343]])

In [136]:
~array1

array([[-10,  -7, -10,  -5],
       [ -6,  -6,  -2,  -4],
       [ -9,  -7,  -6,  -8]])

In [137]:
array1

array([[9, 6, 9, 4],
       [5, 5, 1, 3],
       [8, 6, 5, 7]])

In [138]:
array1>array2

array([[ True,  True,  True, False],
       [ True, False, False, False],
       [ True, False, False,  True]])

In [139]:
#Numpy - String operations

In [140]:
ar = np.array(["hitesh" , "kumar"])

In [141]:
ar

array(['hitesh', 'kumar'], dtype='<U6')

In [142]:
np.char.upper(ar)

array(['HITESH', 'KUMAR'], dtype='<U6')

In [143]:
np.char.capitalize(ar)

array(['Hitesh', 'Kumar'], dtype='<U6')

In [144]:
np.char.title(ar)

array(['Hitesh', 'Kumar'], dtype='<U6')

In [145]:
#Numpy - Mathematical functions.

In [146]:
array1

array([[9, 6, 9, 4],
       [5, 5, 1, 3],
       [8, 6, 5, 7]])

In [147]:
np.sin(array1)

array([[ 0.41211849, -0.2794155 ,  0.41211849, -0.7568025 ],
       [-0.95892427, -0.95892427,  0.84147098,  0.14112001],
       [ 0.98935825, -0.2794155 , -0.95892427,  0.6569866 ]])

In [148]:
np.cos(array1)

array([[-0.91113026,  0.96017029, -0.91113026, -0.65364362],
       [ 0.28366219,  0.28366219,  0.54030231, -0.9899925 ],
       [-0.14550003,  0.96017029,  0.28366219,  0.75390225]])

In [149]:
np.tan(array1)

array([[-0.45231566, -0.29100619, -0.45231566,  1.15782128],
       [-3.38051501, -3.38051501,  1.55740772, -0.14254654],
       [-6.79971146, -0.29100619, -3.38051501,  0.87144798]])

In [150]:
np.log10(array1)

array([[0.95424251, 0.77815125, 0.95424251, 0.60205999],
       [0.69897   , 0.69897   , 0.        , 0.47712125],
       [0.90308999, 0.77815125, 0.69897   , 0.84509804]])

In [151]:
np.exp(array1)

array([[8.10308393e+03, 4.03428793e+02, 8.10308393e+03, 5.45981500e+01],
       [1.48413159e+02, 1.48413159e+02, 2.71828183e+00, 2.00855369e+01],
       [2.98095799e+03, 4.03428793e+02, 1.48413159e+02, 1.09663316e+03]])

In [152]:
np.power(array1, 2)

array([[81, 36, 81, 16],
       [25, 25,  1,  9],
       [64, 36, 25, 49]])

In [153]:
np.mean(array1)

5.666666666666667

In [154]:
np.median(array1)

5.5

In [155]:
np.mode(array1)

AttributeError: module 'numpy' has no attribute 'mode'

In [156]:
np.std(array1)

2.2852182001336816

In [157]:
np.var(array1)

5.222222222222222

In [158]:
np.min(array1)

1

In [159]:
np.max(array1)

9

In [160]:
# Numpy - Arithmetic operations.

In [161]:
array1

array([[9, 6, 9, 4],
       [5, 5, 1, 3],
       [8, 6, 5, 7]])

In [162]:
array2

array([[2, 3, 3, 5],
       [2, 8, 2, 9],
       [5, 6, 6, 3]])

In [163]:
array1-array2

array([[ 7,  3,  6, -1],
       [ 3, -3, -1, -6],
       [ 3,  0, -1,  4]])

In [164]:
np.subtract(array1,array2)

array([[ 7,  3,  6, -1],
       [ 3, -3, -1, -6],
       [ 3,  0, -1,  4]])

In [165]:
np.multiply(array1,array2)

array([[18, 18, 27, 20],
       [10, 40,  2, 27],
       [40, 36, 30, 21]])

In [166]:
np.mod(array1,array2)

array([[1, 0, 0, 4],
       [1, 5, 1, 3],
       [3, 0, 5, 1]])

In [167]:
np.power(array1,array2)

array([[    81,    216,    729,   1024],
       [    25, 390625,      1,  19683],
       [ 32768,  46656,  15625,    343]])

In [168]:
np.sqrt(array1)

array([[3.        , 2.44948974, 3.        , 2.        ],
       [2.23606798, 2.23606798, 1.        , 1.73205081],
       [2.82842712, 2.44948974, 2.23606798, 2.64575131]])

In [169]:
# Numpy - Statistical functions.

In [170]:
array1

array([[9, 6, 9, 4],
       [5, 5, 1, 3],
       [8, 6, 5, 7]])

In [171]:
np.average(array1)

5.666666666666667

In [172]:
np.mean(array1)

5.666666666666667

In [173]:
np.std(array1)

2.2852182001336816

In [174]:
np.median(array1)

5.5

In [186]:
## Sort , Search & Counting  Functions.

In [177]:
aarr = np.array([6,7,3,9,2])

In [178]:
aarr

array([6, 7, 3, 9, 2])

In [179]:
np.sort(aarr)

array([2, 3, 6, 7, 9])

In [182]:
np.searchsorted(aarr, 6)

5

In [184]:
array10 = np.array([0,324,625,65,6,60,0,0,234])

In [185]:
array10

array([  0, 324, 625,  65,   6,  60,   0,   0, 234])

In [186]:
np.count_nonzero(array10)

6

In [187]:
np.where(array10>0)

(array([1, 2, 3, 4, 5, 8]),)

In [190]:
np.extract(array10 > 200, array10)

array([324, 625, 234])

In [191]:
# Numpy - Byte Swapping

In [192]:
array10

array([  0, 324, 625,  65,   6,  60,   0,   0, 234])

In [193]:
aarr

array([6, 7, 3, 9, 2])

In [195]:
aarr.byteswap()

array([432345564227567616, 504403158265495552, 216172782113783808,
       648518346341351424, 144115188075855872])

In [197]:
array10.byteswap(True)

array([                   0,  4900197869555810304,  8143071076239278080,
        4683743612465315840,   432345564227567616,  4323455642275676160,
                          0,                    0, -1585267068834414592])

In [198]:
#Numpy - Copies & views

In [199]:
array1

array([[9, 6, 9, 4],
       [5, 5, 1, 3],
       [8, 6, 5, 7]])

In [200]:
a = np.copy(array1)

In [201]:
a

array([[9, 6, 9, 4],
       [5, 5, 1, 3],
       [8, 6, 5, 7]])

In [202]:
b = array1.view()

In [203]:
b

array([[9, 6, 9, 4],
       [5, 5, 1, 3],
       [8, 6, 5, 7]])

In [204]:
b[0] = 234

In [205]:
b

array([[234, 234, 234, 234],
       [  5,   5,   1,   3],
       [  8,   6,   5,   7]])

In [206]:
array1

array([[234, 234, 234, 234],
       [  5,   5,   1,   3],
       [  8,   6,   5,   7]])

In [207]:
# i.e b=array1

In [209]:
# Numpy - Matrix Library.

In [210]:
import numpy.matlib as nm

In [211]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [212]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [213]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [214]:
# Numpy - Linear Algebra

In [218]:
x = np.random.randint([[2,3], [4,5]])

In [219]:
y = np.random.randint([[5,3], [2,5]])

In [220]:
x

array([[0, 2],
       [2, 1]])

In [221]:
y

array([[4, 1],
       [0, 4]])

In [223]:
np.dot(x,y) # dot product

array([[0, 8],
       [8, 6]])

In [224]:
x@y

array([[0, 8],
       [8, 6]])